【データ管理】ER図作成
bigdragon0610/all-you-need-is-love pull request #16
Opened 2022-08-23 08:31 UTC by hinatakahashi

## What's Changed
- テーブルたたき作成
- リレーションまだです

## Linked Issues
- #6 

## Operation Check with Screenshots
-
<img width="1440" alt="スクリーンショット 2022-08-23 17 30 37" src="https://user-images.githubusercontent.com/74642727/186111219-5529ee5b-b46b-4b98-9710-47e0015061b1.png">

-

2022-09-01 08:35 UTC, daiki-sato requested changes
postテーブルの、nameって何を表しているカラム？

commentsとかが良いかな？

<img width="436" alt="スクリーンショット 2022-09-01 17 35 15" src="https://user-images.githubusercontent.com/71477876/187870268-de65aca2-4be2-41ff-a9d6-0d4e4545f017.png">

2022-09-01 09:01 UTC, daiki-sato requested changes
VARCHAR(255)をVARCHAR(30)くらいに変更お願い


<img width="437" alt="スクリーンショット 2022-09-01 18 01 05" src="https://user-images.githubusercontent.com/71477876/187875589-c2b930bc-a66a-43d2-9d88-a15dd11e4dd8.png">

2022-09-01 09:04 UTC, daiki-sato reviewed
投稿の文字数"5000"で

<img width="517" alt="スクリーンショット 2022-09-01 18 04 14" src="https://user-images.githubusercontent.com/71477876/187876193-aa1a05c9-add0-419c-bfaa-2806d774905e.png">

2022-09-03 04:44 UTC, daiki-sato approved these changes
oke

2022-09-03 04:44 UTC, daiki-sato commented
lgtm

2022-09-03 04:45 UTC, bigdragon0610 approved these changes
lgtm

2022-09-03 04:45 UTC, merged